# Name of the workflow
name: Test unit test cases

# When should this workflow run
on:

  # Runs the workflow when someone pushed into the branch
  push:

# Jobs under this workflow
jobs:
  # Name of the Job
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps / tasks
    steps:
        # Get the code into runner (Machine)
      - name: Get code
        uses: actions/checkout@v4
        # Don't need to install Python again as our runner has already installed it.
        # For more details, check runner page in Github
        # But, here adding install python steps just sake of learning purpose
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        # Install dependencies
        # As previous step installs PIP as inbuilt, here uses poetry for venv
      - name: Install dependencies
        run: |
          pip3 install poetry
          poetry shell
          poetry install
        # Test the unit test cases
      - name: Run unit test cases
        run: pytest tests